name: Multiplatform build & push

on:
  push:
    branches: [ "main" ]
  pull_request:
  
jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    if: github.event_name == 'push'
    
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: reraw-relay
      VERSION: latest
      TAG: ${{ github.ref_name }}

    steps:
      - uses: actions/checkout@v4
        name: Check out code
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"
      - name: Run tests
        run: go test -v ./...
      - name: Docker build
        if: github.actor != 'dependabot[bot]'
        uses: mr-smithers-excellent/docker-build-push@v6
        id: build
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: latest
          registry: ${{ env.REGISTRY }}
          multiPlatform: true
          platform: linux/amd64,linux/arm64
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          addLatest: ${{ startsWith(github.ref, 'refs/tags/v') }}
          buildArgs: TAG=${{ env.TAG }}